### ISSUE TITLE
Type of the game platform

### ISSUE THREAD

**Issue by dotevo** [yancharkin/games_nebula#9]
I know that in my library I have some games with native support and some only for Windows. It will be good if I will see that on my goglib list (like operating system icons).

**Comment by yancharkin** [comment]
I find this feature not very useful. Also there is games that use ScummVM and DOSBox and there is no way to find that before download. How to categorize them?

**Comment by dotevo** [comment]
But you can check if the game is native or for windows. I'm right?

**Comment by yancharkin** [comment]
Sort of. But that info provided by GOG, it's not very reliable. For example, according to GOG:
- 'Two Worlds' is a native Linux game, but it's a wine wrapper
-  'Albion' is a Windows game, but in fact it's not, it's a DOS game. To run it you have to use DOSBox and it doesn't matter if you using Windows, Linux, MacOS, Android or something else
- 'Flight of the Amazon Queen' uses ScummVM, so it can run on Linux same way as on other OSs
- 'Neverwinter Nights' is a Windows-only game, but 'Games Nebula' can download native binaries for Linux
And there is MUCH MORE examples.

Also 'Games Nebula' never uses dosbox or scummvm binaries provided with GOG installers, which makes it even harder to categorize games that uses them.
How to categorize games in example? Is 'Two Worlds' native game? Probably not, but according to GOG it is. Is 'Albion' Windows game? No, but GOG says otherwise.
So feature you requested is hard (or even impossible) to implement and I definitely not going to do that.
